name: Javier Briones
favicon: null
layout_spectrum: 0.16304636280983686
typography_spectrum: 0.3207512404769659
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9228488972876221
  lightness: 0.07719646231271327
  saturation: 0.8271789590362459
  rhythmicContrast: 0.0625713022891432
purpose: []
